name: Build and Push Docker Image

on:
  push:
    branches:
      - container-cd
  pull_request:
    branches:
      - container-cd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Extract metadata from Git/GitHub
      uses: docker/metadata-action@v5
      id: metadata
      with:
        images: jugavi/practica-final-devops

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ steps.metadata.outputs.tags }}
